name: vitalife_app1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tflite_flutter: ^0.11.0
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.7
  carousel_slider: ^5.0.0
  lottie: ^3.1.2
  http: ^1.6.0
  camera: ^0.11.0+2
  image: ^4.2.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/food_translate.csv
    - assets/models/best_float32.tflite
    - assets/models/labels.txt